GitBook: [nosql/mongodb-modules] 54 pages modified
bitprj/bitproject pull request #22
Opened 2020-03-23 00:45 UTC by ismaildude

#### Issues Closed 

- [ ] Closes #9 

...

Changes proposed in this pull request:
* Addition of a RoadMap for NoSQL/MongoDB 

@reviewer/kavuong

2020-03-24 06:39 UTC, kavuong requested changes
Left a few comments with regards to content below! also please restore the python module

2020-03-24 06:39 UTC, kavuong commented on teams/developer-relations/development-roadmap/roadmap-topic-breakdown.md
> +* Students will learn the main difference between NoSQL and SQL databases.
I think the priority here should be the concepts of NoSQL itself, not focusing on SQL at all.

2020-03-24 06:39 UTC, kavuong commented on teams/developer-relations/development-roadmap/roadmap-topic-breakdown.md
> +* Students will learn the main difference between NoSQL and SQL databases.
additionally, there should be some learning objectives about MongoDB's various products - Stitch, Atlas, etc. The MongoDB workshop can provide more insight, and @jeffchhen could also help with this

2020-03-24 06:39 UTC, kavuong commented on teams/developer-relations/development-roadmap/roadmap-topic-breakdown.md
> +* GutenBooks
we should definitely use the Twitter API here haha

2020-03-25 03:48 UTC, ismaildude commented
I have updated this branch please take a look!

2020-03-27 21:00 UTC, merged